SET SERVEROUTPUT ON;


CREATE OR REPLACE PACKAGE BODY URBANUNITS
AS
	K_RAD CONSTANT FLOAT := 57.295779513082;

	FUNCTION DISTANCEKM (COMA IN VARCHAR, COMB IN VARCHAR) RETURN NUMBER;
END URBANUNITS;
/

CREATE OR REPLACE PACKAGE BODY URBANUNITS
AS

	FUNCTION
		DISTANCEKM (COMA IN VARCHAR, COMB IN VARCHAR) RETURN NUMBER
	IS
		LAT_A FLOAT;
		LAT_B FLOAT;
		LONG_A FLOAT;
		LONG_B FLOAT;
	BEGIN
		SELECT LATITUDE, LONGITUDE INTO LAT_A, LONG_A
		FROM COMMUNE WHERE NOM_COM = COMA;

		SELECT LATITUDE, LONGITUDE INTO LAT_B, LONG_B
		FROM COMMUNE WHERE NOM_COM = COMB;

		LAT_A := LAT_A/K_RAD;
		LAT_B := LAT_B/K_RAD;
		LONG_A := LONG_A/K_RAD;
		LONG_B := LONG_B/K_RAD;

		RETURN 6366*ACOS(COS((LAT_A))*COS((LAT_B))*COS((LONG_B)-(LONG_A))+SIN((LAT_A))*SIN((LAT_B)));

		EXCEPTION
		      WHEN NO_DATA_FOUND THEN
		       RAISE_APPLICATION_ERROR(-20010, 'COMMUNE INTROUVABLE');

	END;

END URBANUNITS;
/

-- UTILISATION:
SELECT URBANUNITS.DISTANCEKM('MONTPELLIER', 'PARIS') FROM DUAL;
-- RETURN  594.478432



CREATE OR REPLACE PACKAGE SUPERVISION
AS
	PROCEDURE GETDATAS (NAMETABLE IN VARCHAR);
	PROCEDURE GETCONNECTEDUSERS;
END SUPERVISION;
/


CREATE OR REPLACE
PACKAGE BODY SUPERVISION
AS
	PROCEDURE GETDATAS (NAMETABLE IN VARCHAR)
	IS

	BEGIN

		FOR CUR_VAR IN (SELECT C.COLUMN_NAME, C.DATA_TYPE, K.CONSTRAINT_NAME
		FROM USER_TAB_COLUMNS C
		LEFT JOIN USER_CONS_COLUMNS K ON C.TABLE_NAME=K.TABLE_NAME AND C.COLUMN_NAME=K.COLUMN_NAME
		WHERE C.TABLE_NAME = NAMETABLE)
		LOOP
			 DBMS_OUTPUT.PUT_LINE(CUR_VAR.COLUMN_NAME||' '||CUR_VAR.DATA_TYPE||' '||CUR_VAR.CONSTRAINT_NAME);
		END LOOP;

	END ;

	PROCEDURE GETCONNECTEDUSERS
	IS
	BEGIN
		FOR CUR_VAR IN (SELECT USERNAME, OSUSER, TERMINAL
		FROM V$SESSION
		WHERE USERNAME IS NOT NULL)
		LOOP
			 DBMS_OUTPUT.PUT_LINE(CUR_VAR.USERNAME||' '||CUR_VAR.OSUSER||' '||CUR_VAR.TERMINAL);
		END LOOP;
	END;


END SUPERVISION;
/

-- TEST:
EXEC SUPERVISION.GETDATAS('COMMUNE');
